FROM quay.io/legendu/jupyterhub-more:next

RUN pip3 install aiutil github-rest-api \
    && /scripts/purge_cache.sh

RUN dnf install -y --setopt=install_weak_deps=False valgrind \
    && icon from_github -r coder/code-server -v ">=4.99.0,<4.118.0" -k amd64.rpm -o /tmp/code.rpm \
    && rpm -i /tmp/code.rpm \
    && rm -f /tmp/code.rpm \
    && icon vscode -c --copy --user-dir /etc/vscode/data/User/ \
    && chmod -R 777 /root/ /etc/vscode/ \
    && /scripts/purge_cache.sh

COPY scripts/ /scripts/

ENV SHELL=/bin/bash
