# NAME: legendu/python-nodejs
FROM legendu/python:next

RUN dnf install -y --setopt=install_weak_deps=False \
        nodejs npm \
    && npm install -g n \
    && n lts \
    && /scripts/purge_cache.sh
