# NAME: dclong/jupyterhub-ds
FROM dclong/jupyterhub-more:next

RUN dnf install -y --setopt=install_weak_deps=False \
        cronie words \
        proxychains-ng wget git-lfs \
        highlight \
    && /scripts/purge_cache.sh

RUN pip3 install \
        loguru pysnooper \
        numpy scipy polars pandas 'pyarrow>=0.14.0' \
        scikit-learn lightgbm \
        google-genai \
        graphviz matplotlib bokeh holoviews[recommended] hvplot pyviz_comms \
        tabulate \
        'JPype1>=0.7.0' sqlparse \
        requests[socks] lxml notifiers \
        aiutil[jupyter] github_rest_api \
    && /scripts/purge_cache.sh

COPY settings/proxychains.conf /etc/proxychains.conf

EXPOSE 5006
