FROM quay.io/legendu/python-nodejs:next

RUN pip3 install \
        nbdime jinja2 nbconvert "jupyterlab>=2.1.0,<4.6.0" \
        jupyterlab_widgets ipywidgets jupyterlab_myst \
        jupyterlab-lsp python-lsp-server[all] \
        jupyterlab-code-formatter ruff \
        jupyterlab_vim \
        jupyter-resource-usage \
        jupyter_ai[all] \
    && jupyter labextension disable @axlair/jupyterlab_vim \
    && /scripts/purge_cache.sh

COPY scripts /scripts
COPY settings/*jupyterlab-* /settings/
COPY settings/jupyter_server_config.py /etc/jupyter/
