FROM quay.io/legendu/python-nodejs:next

RUN uv pip install --no-cache --python /opt/venv/bin/python3 \
        nbdime jinja2 nbconvert "jupyterlab>=4.0.0,<4.7.0" euporie \
        jupyterlab_widgets ipywidgets jupyterlab_myst \
        jupyterlab-lsp python-lsp-server[all] \
        jupyterlab-code-formatter ruff \
        jupyterlab_vim \
        jupyter-resource-usage \
        jupyter_ai \
    && jupyter labextension disable @axlair/jupyterlab_vim \
    && /scripts/purge_cache.sh

COPY scripts /scripts
COPY settings/*jupyterlab-* /settings/
COPY settings/jupyter_server_config.py /etc/jupyter/
