# NAME: dclong/base
FROM fedora:latest

SHELL ["/bin/bash", "-O", "extglob", "-c"]
ENV HISTTIMEFORMAT="[%F %T %z]  "

COPY scripts /scripts

RUN dnf install -y --setopt=install_weak_deps=False \
        sudo \
        pkgconf-pkg-config \
        fd-find file zip less \
        tzdata glibc-langpack-en \
        man-db \
        git openssh-clients \
        rsync curl \
    && curl -sSL https://raw.githubusercontent.com/legendu-net/icon/main/install_icon.sh \
        | bash -s -- -v v0.42.0 \
    && /scripts/purge_cache.sh

ARG TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
