# NAME: dclong/jupyterhub-jdk
FROM dclong/jupyterhub:next

RUN dnf install -y --setopt=install_weak_deps=False \
        java-21-openjdk-devel maven gradle \
    && /scripts/purge_cache.sh

COPY scripts /scripts

ENV M2_HOME=/usr/share/maven
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
ENV PATH=$PATH:$JAVA_HOME/bin
