# NAME: legendu/jupyterhub-more
FROM quay.io/legendu/jupyterhub-jdk:next

COPY scripts /scripts

RUN dnf install -y --setopt=install_weak_deps=False fzf \
    && /scripts/purge_cache.sh

RUN npm install -g @google/gemini-cli

# Deno
RUN curl -fsSL https://deno.land/install.sh | sh -s -- --no-modify-path -y \
    && mv /root/.deno/bin/deno /usr/local/bin/ \
    && rm -rf /root/.deno/ \
    && deno jupyter --install \
    && mkdir -p /usr/local/share/jupyter/kernels/ \
    && mv /root/.local/share/jupyter/kernels/deno /usr/local/share/jupyter/kernels/ \
    && /scripts/purge_cache.sh

# Rust kernel
ENV RUSTUP_HOME=/usr/local/rustup PATH=/usr/local/cargo/bin:$PATH
RUN dnf install -y --setopt=install_weak_deps=False cmake \
    && /scripts/purge_cache.sh
COPY --from=quay.io/legendu/rust-utils:next /usr/local/rustup/ /usr/local/rustup/
COPY --from=quay.io/legendu/rust-utils:next /usr/local/cargo/bin /usr/local/cargo/bin
COPY --from=quay.io/legendu/rust-utils:next /usr/bin/nperf /usr/bin/
COPY --from=quay.io/legendu/rust-utils:next /root/.local/share/jupyter/kernels/rust/ /usr/local/share/jupyter/kernels/rust/

# GoLANG
ENV PATH=/usr/local/go/bin:$PATH
RUN icon golang -ic --copy \
    && /scripts/purge_cache.sh

# The Ganymede Java kernel
RUN icon download_github_release -r allen-ball/ganymede -k jar -K asc -o /tmp/ganymede.jar \
    && java -jar /tmp/ganymede.jar -i --sys-prefix \
    && mv /opt/venv/share/jupyter/kernels/ganymede-*-java-*/ /usr/local/share/jupyter/kernels/ \
    && sed -i 's_/opt/venv/share/jupyter/kernels/_/usr/local/share/jupyter/kernels/_g' /usr/local/share/jupyter/kernels/ganymede*/kernel.json \
    && rm -f /tmp/ganymede.jar \
    && /scripts/purge_cache.sh
