FROM quay.io/legendu/base:next

RUN dnf install -y --setopt=install_weak_deps=False \
        pkgconf-pkg-config openssl-devel cmake gcc gcc-c++ make \
    && /scripts/purge_cache.sh

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo PATH=/usr/local/cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y --profile minimal -c rustfmt \
    && /scripts/purge_cache.sh

COPY scripts /scripts
