FROM quay.io/legendu/python:next

RUN pip3 install github-rest-api \
    && /scripts/purge_cache.sh

ENV RUSTUP_HOME=/usr/local/rustup PATH=/usr/local/cargo/bin:$PATH
COPY --from=quay.io/legendu/rust:next /usr/local/rustup/ /usr/local/rustup/
COPY --from=quay.io/legendu/rust:next \
        /usr/local/cargo/bin/rustc \
        /usr/local/cargo/bin/rustdoc \
        /usr/local/cargo/bin/cargo \
        /usr/local/cargo/bin/cargo-fmt \
        /usr/local/cargo/bin/rustfmt \
    /usr/local/cargo/bin/
COPY --from=quay.io/legendu/rust-utils:next /usr/local/cargo/bin/cargo-criterion /usr/local/cargo/bin/
COPY --from=quay.io/legendu/rust-utils:next /usr/bin/nperf /usr/bin/
