# NAME: legendu/jupyterhub-jdk
FROM quay.io/legendu/jupyterhub:next

RUN dnf install -y --setopt=install_weak_deps=False \
        java-25-openjdk-devel maven \
    && /scripts/purge_cache.sh

COPY scripts /scripts

ENV M2_HOME=/usr/share/maven
ENV JAVA_HOME=/usr/lib/jvm/java-25-openjdk
ENV PATH=$PATH:$JAVA_HOME/bin
