FROM registry.fedoraproject.org/fedora-toolbox:latest

COPY scripts /scripts
# purge_cache.sh's canonical copy lives in base-slim/Containerfile instead
# of here, since that image is much smaller (~140MB vs this one's ~1.1GB).
COPY --from=quay.io/legendu/base-slim:next /scripts/purge_cache.sh /scripts/purge_cache.sh

RUN dnf copr enable -y aldantanneo/jj-vcs \
    && dnf install -y --setopt=install_weak_deps=False \
        sudo pkgconf-pkg-config \
        fd-find file zip less \
        tzdata glibc-langpack-en \
        man-db \
        git jj-cli \
        openssh-clients rsync curl \
        neovim fish \
    && curl -sSL https://raw.githubusercontent.com/legendu-net/icon/main/install_icon.sh \
        | bash -s -- -v v0.51.0 \
    && /scripts/purge_cache.sh

# Ghostty sets TERM=xterm-ghostty; Fedora's ncurses-term ships `ghostty` but not
# `xterm-ghostty`. tic's "alias ghostty multiply defined" warning is expected.
COPY ghostty.terminfo /tmp/ghostty.terminfo
RUN tic -x -o /usr/share/terminfo /tmp/ghostty.terminfo \
    && rm -f /tmp/ghostty.terminfo

ARG TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV EDITOR=nvim VISUAL=nvim
