FROM quay.io/legendu/jupyterlab:next

RUN npm install -g configurable-http-proxy \
    && pip3 install "SQLAlchemy<2.0.0" "jupyterhub<6.0.0" \
    && /scripts/purge_cache.sh

COPY settings/jupyterhub_config.py /etc/jupyterhub/
COPY scripts /scripts
