# NAME: legendu/jupyterhub
FROM legendu/jupyterlab:next

RUN npm install -g configurable-http-proxy \
    && pip3 install "SQLAlchemy<2.0.0" "jupyterhub<5.5.0" \
    && /scripts/purge_cache.sh

COPY settings/jupyterhub_config.py /etc/jupyterhub/
COPY scripts /scripts

EXPOSE 3000 8000
