name: Update the Version of icon
on:
  schedule:
    - cron: '0 6 * * *'
      timezone: 'America/Los_Angeles'
jobs:
  update-version-icon:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Update the Version of icon
        run: |
          uvx --from github-rest-api@latest update_version_containerfile \
            --containerfile base/Containerfile \
            --repo legendu-net/icon \
            --pattern '-v v?\d+\.\d+\.\d+' \
            --replace '-v v{version}' \
            --token ${{ secrets.ACTIONS_TOKEN }}


