name: Update the Version of JupyterLab
on:
  schedule:
    - cron: '0 14 * * *'
      timezone: 'America/Los_Angeles'
jobs:
  update-version-jupyterlab:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Update the Version of JupyterLab
        run: |
          curl -sSL https://raw.githubusercontent.com/legendu-net/github_actions_scripts/main/container/update_version_containerfile.py \
            | uv run --script - \
            --containerfile jupyterlab/Containerfile \
            --repo jupyterlab/jupyterlab \
            --token ${{ secrets.GITHUBACTIONS }}

